train:
  _target_: src.datasets.LJspeechDataset
  part: "train"
  instance_transforms: ${transforms.instance_transforms.inference}
val:
  _target_: src.datasets.LJspeechDataset
  part: "test"
  instance_transforms: ${transforms.instance_transforms.inference}
