defaults:
  - model: generator_v3
  - writer: wandb
  - metrics: example
  - datasets: ljspeech
  - dataloader: example
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.Adam
  lr: 2e-4
  weight_decay: 0.01
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.999
  last_epoch: -1
generator_loss_function:
  _target_: src.loss.GeneratorLoss
discriminator_loss_function:
  _target_: src.loss.DiscriminatorLoss
trainer:
  log_step: 5
  n_epochs: 1000
  epoch_len: null
  device_tensors: ["audio"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  # monitor: "max test_MulticlassAccuracy" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 1 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  from_audio: True
  seed: 1
